// The bundled emoji set (#40) — the data half of the emoji provider.
//
// Bundled, and that is the decision worth stating. The alternatives are reading
// the system's own list (there is no such list on Linux — fontconfig knows what
// glyphs a font has, not what they are called) or shipping the full Unicode
// CLDR annotation file (~1,900 emoji and ~15,000 keywords, which is a megabyte
// of QML parsed at startup for a provider most sessions never open).
//
// So: a curated set of what people actually paste, with the keywords that reach
// them. It is deliberately short enough to read. Adding one is a line here and
// nothing else — the search, the ranking and the copy are all in
// EmojiPolicy.qml next door and none of them know how long this list is.
//
// `name` is what the row shows and the first thing matched. `keywords` are how
// you find a glyph whose name you do not know, which is most of them: nobody
// searches for "face with tears of joy", they type "lol". They score lower than
// the name for the reason a desktop entry's keywords do (LauncherPolicy.qml).
//
// Imports nothing but QtQuick, so `tests/` can reach it — including the check
// that no two entries claim the same character.
import QtQuick

QtObject {
    id: table

    readonly property var emoji: [
        // --- faces ------------------------------------------------------------
        { char: "😀", name: "grinning face", keywords: ["smile", "happy", "grin"] },
        { char: "😃", name: "grinning face with big eyes", keywords: ["smile", "happy"] },
        { char: "😄", name: "grinning face with smiling eyes", keywords: ["smile", "happy"] },
        { char: "😁", name: "beaming face", keywords: ["grin", "smile"] },
        { char: "😆", name: "grinning squinting face", keywords: ["laugh", "haha"] },
        { char: "😅", name: "grinning face with sweat", keywords: ["relief", "phew", "nervous"] },
        // Ahead of 🤣, which shares the "lol" keyword with it: ties break on
        // table order, and this is the one people mean.
        { char: "😂", name: "face with tears of joy", keywords: ["lol", "laugh", "cry", "joy"] },
        { char: "🤣", name: "rolling on the floor laughing", keywords: ["rofl", "lol", "laugh"] },
        { char: "🙂", name: "slightly smiling face", keywords: ["smile", "polite"] },
        { char: "🙃", name: "upside-down face", keywords: ["sarcasm", "irony", "silly"] },
        { char: "😉", name: "winking face", keywords: ["wink", "flirt"] },
        { char: "😊", name: "smiling face with smiling eyes", keywords: ["blush", "happy"] },
        { char: "😍", name: "smiling face with heart-eyes", keywords: ["love", "crush"] },
        { char: "😘", name: "face blowing a kiss", keywords: ["kiss", "love"] },
        { char: "😗", name: "kissing face", keywords: ["kiss"] },
        { char: "🤗", name: "hugging face", keywords: ["hug", "embrace"] },
        { char: "🤔", name: "thinking face", keywords: ["hmm", "think", "consider"] },
        { char: "🤨", name: "face with raised eyebrow", keywords: ["skeptic", "suspicious"] },
        { char: "😐", name: "neutral face", keywords: ["meh", "blank", "deadpan"] },
        { char: "😑", name: "expressionless face", keywords: ["blank", "meh"] },
        { char: "😶", name: "face without mouth", keywords: ["silent", "speechless"] },
        { char: "🙄", name: "face with rolling eyes", keywords: ["eyeroll", "whatever"] },
        { char: "😏", name: "smirking face", keywords: ["smug", "smirk"] },
        { char: "😣", name: "persevering face", keywords: ["struggle", "ugh"] },
        { char: "😪", name: "sleepy face", keywords: ["tired", "sleep"] },
        { char: "😴", name: "sleeping face", keywords: ["sleep", "zzz", "tired"] },
        { char: "😌", name: "relieved face", keywords: ["relief", "calm"] },
        { char: "😜", name: "winking face with tongue", keywords: ["silly", "joke"] },
        { char: "🤪", name: "zany face", keywords: ["goofy", "wild", "crazy"] },
        { char: "😎", name: "smiling face with sunglasses", keywords: ["cool", "sunglasses"] },
        { char: "🤓", name: "nerd face", keywords: ["geek", "glasses", "nerd"] },
        { char: "🧐", name: "face with monocle", keywords: ["inspect", "scrutiny"] },
        { char: "😕", name: "confused face", keywords: ["confused", "unsure"] },
        { char: "😟", name: "worried face", keywords: ["worry", "concern"] },
        { char: "🙁", name: "slightly frowning face", keywords: ["sad", "frown"] },
        { char: "😮", name: "face with open mouth", keywords: ["surprise", "wow"] },
        { char: "😯", name: "hushed face", keywords: ["surprise", "quiet"] },
        { char: "😲", name: "astonished face", keywords: ["shock", "gasp", "wow"] },
        { char: "😳", name: "flushed face", keywords: ["embarrassed", "blush"] },
        { char: "🥺", name: "pleading face", keywords: ["please", "beg", "puppy"] },
        { char: "😦", name: "frowning face with open mouth", keywords: ["sad", "shock"] },
        { char: "😨", name: "fearful face", keywords: ["scared", "fear"] },
        { char: "😰", name: "anxious face with sweat", keywords: ["nervous", "anxious"] },
        { char: "😥", name: "sad but relieved face", keywords: ["sad", "phew"] },
        { char: "😢", name: "crying face", keywords: ["sad", "cry", "tear"] },
        { char: "😭", name: "loudly crying face", keywords: ["sob", "cry", "sad"] },
        { char: "😱", name: "face screaming in fear", keywords: ["scream", "shock", "horror"] },
        { char: "😖", name: "confounded face", keywords: ["frustrated", "ugh"] },
        { char: "😞", name: "disappointed face", keywords: ["sad", "let down"] },
        { char: "😓", name: "downcast face with sweat", keywords: ["sad", "work"] },
        { char: "😩", name: "weary face", keywords: ["tired", "exhausted"] },
        { char: "😫", name: "tired face", keywords: ["tired", "exhausted", "done"] },
        { char: "🥱", name: "yawning face", keywords: ["bored", "tired", "yawn"] },
        { char: "😤", name: "face with steam from nose", keywords: ["triumph", "determined"] },
        { char: "😡", name: "enraged face", keywords: ["angry", "mad", "rage"] },
        { char: "😠", name: "angry face", keywords: ["angry", "mad"] },
        { char: "🤬", name: "face with symbols on mouth", keywords: ["swear", "curse", "angry"] },
        { char: "😷", name: "face with medical mask", keywords: ["sick", "mask", "ill"] },
        { char: "🤒", name: "face with thermometer", keywords: ["sick", "fever", "ill"] },
        { char: "🤢", name: "nauseated face", keywords: ["sick", "gross", "yuck"] },
        { char: "🤮", name: "face vomiting", keywords: ["sick", "vomit", "gross"] },
        { char: "🥳", name: "partying face", keywords: ["party", "celebrate", "birthday"] },
        { char: "🥵", name: "hot face", keywords: ["heat", "sweat", "hot"] },
        { char: "🥶", name: "cold face", keywords: ["freezing", "cold"] },
        { char: "😵", name: "face with crossed-out eyes", keywords: ["dizzy", "dead", "knocked out"] },
        { char: "🤯", name: "exploding head", keywords: ["mind blown", "shock", "wow"] },
        { char: "🤠", name: "cowboy hat face", keywords: ["cowboy", "yeehaw"] },
        { char: "🤡", name: "clown face", keywords: ["clown", "joker"] },
        { char: "👻", name: "ghost", keywords: ["boo", "halloween", "spooky"] },
        { char: "💀", name: "skull", keywords: ["dead", "death", "skull"] },
        { char: "☠️", name: "skull and crossbones", keywords: ["danger", "poison", "death"] },
        { char: "👽", name: "alien", keywords: ["ufo", "extraterrestrial", "space"] },
        { char: "🤖", name: "robot", keywords: ["bot", "ai", "machine"] },
        { char: "💩", name: "pile of poo", keywords: ["poop", "crap", "shit"] },

        // --- gestures and people ---------------------------------------------
        { char: "👋", name: "waving hand", keywords: ["wave", "hello", "bye"] },
        { char: "🤚", name: "raised back of hand", keywords: ["hand", "stop"] },
        { char: "✋", name: "raised hand", keywords: ["stop", "high five", "hand"] },
        { char: "👌", name: "OK hand", keywords: ["ok", "perfect", "good"] },
        { char: "🤏", name: "pinching hand", keywords: ["small", "tiny", "little"] },
        { char: "✌️", name: "victory hand", keywords: ["peace", "two", "v"] },
        { char: "🤞", name: "crossed fingers", keywords: ["luck", "hope", "fingers crossed"] },
        { char: "🤟", name: "love-you gesture", keywords: ["love", "ily"] },
        { char: "🤘", name: "sign of the horns", keywords: ["rock", "metal"] },
        { char: "🤙", name: "call me hand", keywords: ["shaka", "hang loose", "call"] },
        { char: "👈", name: "backhand index pointing left", keywords: ["point", "left"] },
        { char: "👉", name: "backhand index pointing right", keywords: ["point", "right"] },
        { char: "👆", name: "backhand index pointing up", keywords: ["point", "up", "this"] },
        { char: "👇", name: "backhand index pointing down", keywords: ["point", "down"] },
        { char: "☝️", name: "index pointing up", keywords: ["point", "one", "actually"] },
        { char: "👍", name: "thumbs up", keywords: ["yes", "like", "approve", "+1", "lgtm"] },
        { char: "👎", name: "thumbs down", keywords: ["no", "dislike", "-1"] },
        { char: "✊", name: "raised fist", keywords: ["fist", "power", "solidarity"] },
        { char: "👊", name: "oncoming fist", keywords: ["punch", "fist bump", "bro"] },
        { char: "👏", name: "clapping hands", keywords: ["applause", "clap", "bravo"] },
        { char: "🙌", name: "raising hands", keywords: ["celebrate", "hooray", "praise"] },
        { char: "🤝", name: "handshake", keywords: ["deal", "agree", "shake"] },
        { char: "🙏", name: "folded hands", keywords: ["please", "thanks", "pray", "namaste"] },
        { char: "💪", name: "flexed biceps", keywords: ["strong", "muscle", "gym"] },
        { char: "🧠", name: "brain", keywords: ["smart", "think", "mind"] },
        { char: "👀", name: "eyes", keywords: ["look", "watch", "see", "shifty"] },
        { char: "🫡", name: "saluting face", keywords: ["salute", "yes sir", "respect"] },
        { char: "🤷", name: "person shrugging", keywords: ["shrug", "dunno", "idk"] },
        { char: "🤦", name: "person facepalming", keywords: ["facepalm", "smh", "ugh"] },
        { char: "💃", name: "woman dancing", keywords: ["dance", "party"] },
        { char: "🕺", name: "man dancing", keywords: ["dance", "party"] },
        { char: "👶", name: "baby", keywords: ["infant", "child"] },

        // --- hearts and symbols ----------------------------------------------
        { char: "❤️", name: "red heart", keywords: ["love", "heart"] },
        { char: "🧡", name: "orange heart", keywords: ["love", "heart"] },
        { char: "💛", name: "yellow heart", keywords: ["love", "heart"] },
        { char: "💚", name: "green heart", keywords: ["love", "heart"] },
        { char: "💙", name: "blue heart", keywords: ["love", "heart"] },
        { char: "💜", name: "purple heart", keywords: ["love", "heart"] },
        { char: "🖤", name: "black heart", keywords: ["love", "heart", "dark"] },
        { char: "🤍", name: "white heart", keywords: ["love", "heart"] },
        { char: "💔", name: "broken heart", keywords: ["sad", "heartbreak"] },
        { char: "💯", name: "hundred points", keywords: ["100", "perfect", "score"] },
        { char: "💥", name: "collision", keywords: ["boom", "explode", "bang"] },
        { char: "✨", name: "sparkles", keywords: ["shiny", "magic", "clean", "new"] },
        { char: "⭐", name: "star", keywords: ["star", "favourite", "favorite"] },
        { char: "🌟", name: "glowing star", keywords: ["star", "shine"] },
        { char: "🔥", name: "fire", keywords: ["hot", "lit", "flame", "burn"] },
        { char: "⚡", name: "high voltage", keywords: ["lightning", "fast", "zap", "power"] },
        { char: "❄️", name: "snowflake", keywords: ["cold", "snow", "winter", "freeze"] },
        { char: "💧", name: "droplet", keywords: ["water", "drop"] },
        { char: "🌊", name: "water wave", keywords: ["ocean", "sea", "wave"] },
        { char: "☀️", name: "sun", keywords: ["sunny", "weather", "hot", "light"] },
        { char: "🌙", name: "crescent moon", keywords: ["night", "moon", "dark"] },
        { char: "☁️", name: "cloud", keywords: ["weather", "cloudy", "sky"] },
        { char: "🌈", name: "rainbow", keywords: ["pride", "colour", "color", "weather"] },
        { char: "✅", name: "check mark button", keywords: ["done", "yes", "tick", "pass", "ok"] },
        { char: "☑️", name: "check box with check", keywords: ["done", "tick", "todo"] },
        { char: "❌", name: "cross mark", keywords: ["no", "wrong", "fail", "x"] },
        { char: "⚠️", name: "warning", keywords: ["caution", "alert", "warning"] },
        { char: "🚫", name: "prohibited", keywords: ["no", "ban", "forbidden", "stop"] },
        { char: "❓", name: "question mark", keywords: ["question", "help", "what"] },
        { char: "❗", name: "exclamation mark", keywords: ["important", "alert", "bang"] },
        { char: "🔴", name: "red circle", keywords: ["dot", "record", "stop"] },
        { char: "🟢", name: "green circle", keywords: ["dot", "go", "ok"] },
        { char: "🟡", name: "yellow circle", keywords: ["dot", "warn"] },
        { char: "🔵", name: "blue circle", keywords: ["dot"] },
        { char: "🔶", name: "large orange diamond", keywords: ["diamond"] },
        { char: "♻️", name: "recycling symbol", keywords: ["recycle", "reuse", "green"] },
        { char: "🔒", name: "locked", keywords: ["lock", "secure", "private"] },
        { char: "🔓", name: "unlocked", keywords: ["unlock", "open"] },
        { char: "🔑", name: "key", keywords: ["key", "password", "access"] },
        { char: "🔔", name: "bell", keywords: ["notification", "alert", "ring"] },
        { char: "🔕", name: "bell with slash", keywords: ["mute", "silent", "quiet"] },

        // --- objects and work -------------------------------------------------
        { char: "💻", name: "laptop", keywords: ["computer", "code", "work"] },
        { char: "🖥️", name: "desktop computer", keywords: ["computer", "monitor", "screen"] },
        { char: "⌨️", name: "keyboard", keywords: ["type", "input", "keys"] },
        { char: "🖱️", name: "computer mouse", keywords: ["mouse", "click"] },
        { char: "📱", name: "mobile phone", keywords: ["phone", "mobile", "cell"] },
        { char: "🔌", name: "electric plug", keywords: ["power", "plug", "charge"] },
        { char: "🔋", name: "battery", keywords: ["power", "charge", "battery"] },
        { char: "💾", name: "floppy disk", keywords: ["save", "disk", "old"] },
        { char: "📦", name: "package", keywords: ["box", "ship", "release", "parcel"] },
        { char: "📁", name: "file folder", keywords: ["folder", "directory", "files"] },
        { char: "📄", name: "page facing up", keywords: ["document", "file", "paper"] },
        { char: "📝", name: "memo", keywords: ["note", "write", "edit", "todo"] },
        { char: "📌", name: "pushpin", keywords: ["pin", "location", "important"] },
        { char: "📎", name: "paperclip", keywords: ["attach", "clip", "file"] },
        { char: "✏️", name: "pencil", keywords: ["write", "edit", "draw"] },
        { char: "🔍", name: "magnifying glass tilted left", keywords: ["search", "find", "zoom", "look"] },
        { char: "🔧", name: "wrench", keywords: ["tool", "fix", "config", "settings"] },
        { char: "🔨", name: "hammer", keywords: ["build", "tool", "fix"] },
        { char: "🐛", name: "bug", keywords: ["bug", "insect", "defect", "issue"] },
        { char: "🚀", name: "rocket", keywords: ["launch", "ship", "deploy", "fast", "space"] },
        { char: "🎯", name: "bullseye", keywords: ["target", "goal", "hit", "aim"] },
        { char: "🧪", name: "test tube", keywords: ["test", "experiment", "science", "lab"] },
        { char: "⚙️", name: "gear", keywords: ["settings", "config", "cog", "options"] },
        { char: "🗑️", name: "wastebasket", keywords: ["trash", "delete", "bin", "remove"] },
        { char: "💡", name: "light bulb", keywords: ["idea", "tip", "hint", "light"] },
        { char: "📊", name: "bar chart", keywords: ["chart", "graph", "stats", "data"] },
        { char: "📈", name: "chart increasing", keywords: ["up", "growth", "graph", "profit"] },
        { char: "📉", name: "chart decreasing", keywords: ["down", "loss", "graph", "drop"] },
        { char: "🗓️", name: "spiral calendar", keywords: ["calendar", "date", "schedule"] },
        { char: "⏰", name: "alarm clock", keywords: ["time", "alarm", "wake", "clock"] },
        { char: "⏳", name: "hourglass not done", keywords: ["wait", "time", "loading"] },
        { char: "🔗", name: "link", keywords: ["url", "chain", "link"] },
        { char: "💬", name: "speech balloon", keywords: ["chat", "talk", "comment", "message"] },
        { char: "📣", name: "megaphone", keywords: ["announce", "loud", "shout"] },
        { char: "🎉", name: "party popper", keywords: ["party", "celebrate", "congrats", "yay"] },
        { char: "🎁", name: "wrapped gift", keywords: ["present", "gift", "birthday"] },
        { char: "🏆", name: "trophy", keywords: ["win", "prize", "award", "first"] },
        { char: "🎵", name: "musical note", keywords: ["music", "song", "note"] },
        { char: "🎧", name: "headphone", keywords: ["music", "audio", "listen"] },
        { char: "📷", name: "camera", keywords: ["photo", "picture", "snap"] },
        { char: "🎬", name: "clapper board", keywords: ["film", "movie", "action", "video"] },
        { char: "📺", name: "television", keywords: ["tv", "watch", "screen"] },
        { char: "☕", name: "hot beverage", keywords: ["coffee", "tea", "drink", "break"] },
        { char: "🍕", name: "pizza", keywords: ["food", "slice", "italian"] },
        { char: "🍔", name: "hamburger", keywords: ["food", "burger"] },
        { char: "🍺", name: "beer mug", keywords: ["beer", "drink", "pub"] },
        { char: "🍰", name: "shortcake", keywords: ["cake", "dessert", "birthday"] },
        { char: "🍎", name: "red apple", keywords: ["fruit", "apple", "food"] },

        // --- nature and travel ------------------------------------------------
        { char: "🌲", name: "evergreen tree", keywords: ["tree", "forest", "pine", "wood"] },
        { char: "🌳", name: "deciduous tree", keywords: ["tree", "forest", "wood"] },
        { char: "🌿", name: "herb", keywords: ["plant", "leaf", "green"] },
        { char: "🍃", name: "leaf fluttering in wind", keywords: ["leaf", "wind", "nature"] },
        { char: "🌸", name: "cherry blossom", keywords: ["flower", "spring", "sakura"] },
        { char: "🌻", name: "sunflower", keywords: ["flower", "sun"] },
        { char: "🍄", name: "mushroom", keywords: ["fungus", "forest"] },
        { char: "🌍", name: "globe showing Europe-Africa", keywords: ["earth", "world", "globe"] },
        { char: "🏔️", name: "snow-capped mountain", keywords: ["mountain", "peak", "alps"] },
        { char: "🏕️", name: "camping", keywords: ["camp", "tent", "outdoors"] },
        { char: "🐺", name: "wolf", keywords: ["animal", "wild"] },
        { char: "🦊", name: "fox", keywords: ["animal", "firefox"] },
        { char: "🐧", name: "penguin", keywords: ["animal", "linux", "tux"] },
        { char: "🐍", name: "snake", keywords: ["animal", "python"] },
        { char: "🐳", name: "spouting whale", keywords: ["animal", "docker", "sea"] },
        { char: "🐙", name: "octopus", keywords: ["animal", "git", "sea"] },
        { char: "🐱", name: "cat face", keywords: ["animal", "cat", "kitty"] },
        { char: "🐶", name: "dog face", keywords: ["animal", "dog", "puppy"] },
        { char: "🚗", name: "automobile", keywords: ["car", "drive", "travel"] },
        { char: "✈️", name: "airplane", keywords: ["plane", "fly", "travel"] },
        { char: "🚂", name: "locomotive", keywords: ["train", "rail", "travel"] },
        { char: "🚲", name: "bicycle", keywords: ["bike", "cycle"] },
        { char: "🏠", name: "house", keywords: ["home", "house"] }
    ]
}
