#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — the stages already done are cheap to repeat.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# ask KEY "Prompt" — read a value into $KEY. Visible input (non-secret).
#
# No remembered default: nothing this wizard collects is kept anywhere it could
# read back. The client id and secret go straight into google-oauth.json at
# 0600, which is the one file that may hold them.
ask() {
  local key="$1" prompt="$2" input
  printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  read -r input || true
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" input
  printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  read -rs input || true
  printf '\n'
  printf -v "$key" '%s' "$input"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────
#
# Eight of them, and each is a thing only a person can do: Google's console has
# no API for creating its own OAuth client, and the consent screen is a browser
# and a password. Everything either side of that — writing the credentials file
# 0600, running the flow, reading the account back — the script does.
#
# Google's *device* flow, the one that shows a code on a TV, does not permit
# Calendar scopes. A desktop client with a loopback redirect on 127.0.0.1 is
# therefore the only path, which is why stage 4 insists on "Desktop app" and why
# stage 6 needs a browser on this machine.

TOTAL_STAGES=8

REPO=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)
OAUTH_FILE="${FOREST_GCAL_OAUTH:-${XDG_CONFIG_HOME:-$HOME/.config}/forest-shell/google-oauth.json}"
TOKEN_FILE="${FOREST_GCAL_TOKEN:-${XDG_DATA_HOME:-$HOME/.local/share}/forest-shell/calendar/google-token.json}"
SHELL_QML="$REPO/shell.qml"

CONSOLE_CREDENTIALS="https://console.cloud.google.com/apis/credentials"
CONSOLE_LIBRARY="https://console.cloud.google.com/apis/library/calendar-json.googleapis.com"
CONSOLE_CONSENT="https://console.cloud.google.com/auth/audience"

banner "Connect forest-shell's calendar to Google"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "A Google Cloud project"
say "Every OAuth client belongs to a project. Any project will do, including"
say "one you already have — the calendar this connects to is chosen later, by"
say "the account you sign in as, not by the project."
open_url "$CONSOLE_CREDENTIALS"
step "Use the project picker in the top bar: pick an existing project, or"
step "  'New project', name it anything (forest-shell reads well), and create it."
step "Wait for the picker to show the project you want before continuing."
pause "Project selected?"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Enable the Google Calendar API"
say "A project can hold an OAuth client for an API it cannot call. Enabling the"
say "Calendar API in this project is what makes the token the client issues"
say "worth anything."
open_url "$CONSOLE_LIBRARY"
step "Check the project name at the top is the one you just picked."
step "Click 'Enable'. If it already says 'Manage', it is on — nothing to do."
pause "Calendar API enabled?"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "The consent screen, and you as a test user"
say "This is the screen you will see in stage 6. Google will not issue a token"
say "until it exists, and an unverified app only issues them to test users —"
say "so the account you want to sync has to be named as one here."
open_url "$CONSOLE_CONSENT"
step "If the project has no consent screen yet, create one: user type"
step "  'External', an app name, your own address for both support fields."
step "User type must be 'External'. 'Internal' exists only inside a Workspace"
step "  organisation and will not let a personal account through."
step "Under 'Test users', click 'Add users' and add the Google address whose"
step "  calendar you want. Save."
warn "Leave publishing status on 'Testing'. Publishing sends the app for review it does not need."
note "A testing-mode refresh token expires after 7 days; re-run stage 6 when it does."
pause "Consent screen configured, and your address listed as a test user?"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Create the OAuth client — Desktop app"
say "Application type decides which flows Google will run. Desktop app is the"
say "one that permits a loopback redirect to 127.0.0.1, which is how the helper"
say "catches the code without a web server."
open_url "$CONSOLE_CREDENTIALS"
step "'+ Create credentials' → 'OAuth client ID'."
step "Application type: 'Desktop app'. Name it anything."
step "Create. Keep the dialog with the client ID and client secret open —"
step "  the next stage asks you to paste both."
warn "'Web application' will fail at stage 6: it refuses the loopback redirect."
pause "Client created, ID and secret on screen?"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Store the client credentials"
say "These go to a file only you can read:"
note "  $OAUTH_FILE"
if [[ -f "$OAUTH_FILE" ]]; then
  EXISTING_ID=$(python3 -c 'import json,sys
try:
    o = json.load(open(sys.argv[1]))
except Exception:
    raise SystemExit(0)
o = o.get("installed", o)
print(o.get("client_id", ""))' "$OAUTH_FILE" 2>/dev/null || true)
  if [[ -n "${EXISTING_ID:-}" ]]; then
    note "already there: ${EXISTING_ID:0:24}…"
    if ! confirm "Replace it with a different client?"; then
      note "keeping the credentials already on disk"
      CLIENT_ID=""
    fi
  fi
fi
if [[ "${CLIENT_ID-unset}" != "" ]]; then
  step "Copy the 'Client ID' — it ends in .apps.googleusercontent.com."
  ask CLIENT_ID "Paste the client ID:"
  while [[ -z "$CLIENT_ID" ]]; do
    warn "a client ID is required"
    ask CLIENT_ID "Paste the client ID:"
  done
  step "Copy the 'Client secret'. Nothing is echoed while you paste it."
  ask_secret CLIENT_SECRET "Paste the client secret:"
  while [[ -z "$CLIENT_SECRET" ]]; do
    warn "a client secret is required for a desktop client"
    ask_secret CLIENT_SECRET "Paste the client secret:"
  done
  mkdir -p -- "$(dirname -- "$OAUTH_FILE")"
  ( umask 077
    FS_CLIENT_ID="$CLIENT_ID" FS_CLIENT_SECRET="$CLIENT_SECRET" \
    python3 -c 'import json, os, sys
path = sys.argv[1]
blob = {"installed": {"client_id": os.environ["FS_CLIENT_ID"],
                      "client_secret": os.environ["FS_CLIENT_SECRET"]}}
fd = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
with os.fdopen(fd, "w") as fh:
    json.dump(blob, fh, indent=2)
    fh.write("\n")
os.chmod(path, 0o600)' "$OAUTH_FILE" )
  unset CLIENT_SECRET
  printf '  %s✓ wrote%s %s (0600)\n' "$GREEN" "$RESET" "$OAUTH_FILE"
fi
pause "Ready to authorise?"

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Authorise — the consent flow"
say "This opens a browser, waits on 127.0.0.1 for the code Google redirects"
say "back, and exchanges it for tokens. The tokens go to:"
note "  $TOKEN_FILE (0600)"
say "Nothing but the account's address is ever printed."
warn "A first-run screen says the app isn't verified: 'Advanced' → 'Go to … (unsafe)'."
warn "That warning is about the unverified app — your own — and not about the scope."
pause "Press Enter to start the flow"
AUTH_JSON=""
if AUTH_JSON=$(cd -- "$REPO" && python3 tools/gcal-sync.py auth); then
  AUTH_EMAIL=$(printf '%s' "$AUTH_JSON" | python3 -c 'import json,sys
try:
    print(json.load(sys.stdin).get("email", ""))
except Exception:
    print("")' 2>/dev/null || true)
  if [[ -n "${AUTH_EMAIL:-}" ]]; then
    printf '  %s✓ connected%s %s\n' "$GREEN" "$RESET" "$AUTH_EMAIL"
  else
    printf '  %s✓ connected%s\n' "$GREEN" "$RESET"
    note "the helper answered without an address; \`python3 tools/gcal-sync.py status\` will say more"
  fi
else
  warn "the flow did not complete — the helper's own diagnosis is above"
  note "exit 3 means Google declined: check the test-user list from stage 3"
  SKIPPED+=("authorise the account: python3 tools/gcal-sync.py auth")
fi
pause

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Turn sync on"
say "The shell spawns no helper and makes no request until this is on, so a"
say "connected account on its own changes nothing."
note "settings key: calendar.google.enabled — no CLI verb sets it; the window does"
if command -v qs >/dev/null 2>&1; then
  step "Opening Settings on its Calendar tab (needs the shell already running)."
  qs -p "$SHELL_QML" ipc call settings showTab calendar >/dev/null 2>&1 \
    || warn "no running instance answered — open Settings yourself, or start the shell with: qs -p $SHELL_QML"
else
  warn "\`qs\` is not on PATH — open Settings by hand"
fi
step "Settings → Calendar → 'Sync with Google': switch it on."
step "Leave 'Calendar' on 'primary' unless you sync a shared one; leave the"
step "  round interval at 5 minutes."
note "a shared calendar's id is an address — Google Calendar shows it as that calendar's Calendar ID"
pause "Sync switched on?"

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "First sync"
say "One round now, then the shell's own answer about how it went."
if command -v qs >/dev/null 2>&1; then
  if qs -p "$SHELL_QML" ipc call calendar sync >/dev/null 2>&1; then
    printf '  %s✓ round requested%s\n' "$GREEN" "$RESET"
    STATUS=$(qs -p "$SHELL_QML" ipc call calendar syncStatus 2>/dev/null || true)
    case "${STATUS:-}" in
      idle)    printf '  %s✓ status%s idle — the round finished\n' "$GREEN" "$RESET" ;;
      syncing) note "status: syncing — still running; ask again in a moment" ;;
      auth)    warn "status: auth — no account is connected; re-run stage 6" ;;
      error)   warn "status: error — the shell log has the code (calendar: sync error …)" ;;
      off)     warn "status: off — sync is still disabled; re-check stage 7" ;;
      *)       note "status: ${STATUS:-<no answer>}" ;;
    esac
  else
    warn "no running instance answered"
    SKIPPED+=("run a first sync: qs -p $SHELL_QML ipc call calendar sync")
  fi
else
  SKIPPED+=("run a first sync: qs -p $SHELL_QML ipc call calendar sync")
fi
say "Open the calendar window: this week's Google events should be in it, and"
say "an event created here should appear in Google within a round."
note "the shell logs one line per round: calendar: sync pull N changes"
pause

finish
note "credentials: $OAUTH_FILE (0600)"
note "tokens:      $TOKEN_FILE (0600)"
note "neither ever reaches the shell, its log, or settings.json"
printf '\n'
